FC-InnerCircle-ICD2/O2O-BE

.github/workflows/admin-cd.yml, .github/workflows/client-cd.yml, .github/workflows/develop-admin-deploy-v1.yml, .github/workflows/develop-client-deploy-v1.yml, .github/workflows/pr-ci.yml, .github/workflows/pull-request-test-v1.yml, application-admin/Dockerfile, application-admin/build.gradle.kts, application-admin/src/test/kotlin/org/fastcampus/applicationadmin/ApplicationAdminApplicationTests.kt, application-client/Dockerfile, application-client/build.gradle.kts, application-client/src/main/kotlin/org/fastcampus/applicationclient/ApplicationClientApplication.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/ApplicationClientApplicationTests.kt, build.gradle.kts, common/build.gradle.kts, common/src/test/kotlin/org/fastcampus/common/CommonApplicationTests.kt, domains/member/build.gradle.kts, domains/member/src/test/kotlin/org/fastcampus/member/MemberApplicationTests.kt, domains/order/build.gradle.kts, domains/order/src/test/kotlin/org/fastcampus/order/OrderApplicationTests.kt, domains/review/build.gradle.kts, domains/review/src/test/kotlin/org/fastcampus/review/ReviewApplicationTests.kt, domains/store/build.gradle.kts, domains/store/src/test/kotlin/org/fastcampus/store/StoreApplicationTests.kt, infrastructure/store-redis/build.gradle.kts, infrastructure/store-redis/src/test/kotlin/org/fastcampus/store/redis/StoreRedisApplicationTests.kt
admin-app 서비스 배포 CI / CD (O)
client-app 서비스 배포 CI / CD (O)
PR Test CI / CD (O)
ktlint 자동 포맷팅 (X)
=> [CHORE] CI / CD 초기 구성

.idea/dataSources.xml, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/StoreController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/dto/response/StoreDetailsResponse.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/service/StoreService.kt, application-client/src/main/resources/http/store.http, application-client/src/test/kotlin/org/fastcampus/applicationclient/store/service/StoreServiceTest.kt, common/src/main/kotlin/org/fastcampus/common/dto/CursorBasedDTO.kt, docker-compose.yml, domains/store/src/main/kotlin/org/fastcampus/store/entity/Menu.kt, domains/store/src/main/kotlin/org/fastcampus/store/entity/MenuOption.kt, domains/store/src/main/kotlin/org/fastcampus/store/entity/MenuOptionGroup.kt, domains/store/src/main/kotlin/org/fastcampus/store/entity/Store.kt, domains/store/src/main/kotlin/org/fastcampus/store/entity/StoreMenuCategory.kt, infrastructure/order-postgres/src/main/resources/application-order-postgres.yml, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/document/MenuDocument.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/document/MenuOptionDocument.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/document/MenuOptionGroupDocument.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/document/StoreDocument.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/document/StoreMenuCategoryDocument.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/repository/StoreMongoRepository.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/repository/StoreMongoRepositoryCustom.kt
=> [FEAT] 점포 상세 조회 API 두개의 API 로 분리하여 개발(#14)

application-client/src/main/kotlin/org/fastcampus/applicationclient/handler/ClientExceptionHandler.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/dto/response/StoreDetailsResponse.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/mapper/StoreExtensions.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/mapper/StoreMapper.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/service/StoreService.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/utils/PaginationUtils.kt, application-client/src/main/resources/http/store.http, application-client/src/test/kotlin/org/fastcampus/applicationclient/store/service/StoreServiceTest.kt, domains/store/src/main/kotlin/org/fastcampus/store/exception/StoreCoordinatesException.kt, domains/store/src/main/kotlin/org/fastcampus/store/exception/StoreException.kt
- 서비스 로직 개선
- 도메인 중심적 설계로 리팩토링
- 확장 함수를 활용한 코드 구조화
- 커스텀 예외 처리 추가
- 불변성 및 null 안전성 강화
Technical:
- 도메인 로직 분리 및 Value Object 도입
=> [Refactor] 서비스 로직 개선 및 단위 테스트 추가(#14)

.github/workflows/develop-admin-deploy-v1.yml, .github/workflows/develop-client-deploy-v1.yml, .github/workflows/pull-request-test-v1.yml, application-admin/build.gradle.kts, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/OrderController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/OrderService.kt, build.gradle.kts, docker-compose.yml, domains/order/src/main/kotlin/org/fastcampus/order/repository/OrderRepository.kt, infrastructure/order-postgres/docker/init-script/01-schema.sql, infrastructure/order-postgres/src/main/kotlin/org/fastcampus/order/postgres/repository/OrderJpaRepositoryCustom.kt, infrastructure/order-postgres/src/main/resources/application-order-postgres.yml
- Fix: 주문 조회 페이징 컬럼 수정
- Fix: schema.sql created_by, updated_by nullable 수정
- Chore: ci 파이프라인 오류 수정
=> [Fix] 주문 조회 페이징 컬럼 수정

application-admin/build.gradle.kts, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/ApplicationAdminApplication.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/order/controller/OrderController.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/order/controller/dto/OrderInquiryResponse.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/order/controller/dto/OrderMenuInquiryResponse.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/order/controller/dto/OrderMenuOptionGroupInquiryResponse.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/order/controller/dto/OrderMenuOptionInquiryResponse.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/order/service/OrderService.kt, application-admin/src/main/resources/application.properties, application-admin/src/main/resources/application.yml, application-admin/src/test/kotlin/org/fastcampus/applicationadmin/fixture/OrderFixture.kt, application-admin/src/test/kotlin/org/fastcampus/applicationadmin/service/OrderServiceTest.kt, domains/order/src/main/kotlin/org/fastcampus/order/entity/Order.kt, domains/order/src/main/kotlin/org/fastcampus/order/repository/OrderRepository.kt, infrastructure/order-postgres/src/main/kotlin/org/fastcampus/order/postgres/repository/OrderJpaRepository.kt, infrastructure/order-postgres/src/main/kotlin/org/fastcampus/order/postgres/repository/OrderJpaRepositoryCustom.kt
점주 앱에서의 주문 목록 조회에 대해서 구현하였습니다.
코드 리뷰는 언제나 환영입니다. 자유롭게 리뷰해주시면 감사하겠습니다!
=> [Feat] (점주) 주문 목록 조회 구현 (#8)

application-admin/src/main/kotlin/org/fastcampus/applicationadmin/config/security/SecurityConfig.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/config/security/dto/AuthMember.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/config/security/dto/JwtAuthenticated.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/config/security/filter/JwtAuthenticationFilter.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/config/security/filter/JwtAuthorizationFilter.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/handler/CeoExceptionHandler.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/config/security/SecurityConfig.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/config/security/dto/AuthMember.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/config/security/dto/JwtAuthenticated.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/config/security/filter/JwtAuthenticationFilter.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/config/security/filter/JwtAuthorizationFilter.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/handler/ClientExceptionHandler.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/member/controller/MemberController.kt
로그인 -> 고객 -> ClientExceptionHandler -> 인가 처리 추가
로그인 -> 점주 -> JwtAuthenticationFilter -> 유효성 검증 추가
로그인 -> 점주 -> SecurityConfig -> 인증, 인가 추가
=> 로그인 -> 고객 -> JwtAuthenticationFilter -> 유효성 검증 추가

application-admin/src/main/resources/logback-spring.xml, application-admin/src/main/resources/logback-variables.properties, application-client/src/main/resources/logback-spring.xml, application-client/src/main/resources/logback-variables.properties, docker-compose.yml
=> [Chore] 로깅설정 (#79)

application-admin/src/main/resources/application.yml, application-client/src/main/resources/application.yml, docker-compose.yml
=> [Chore] 실행포트 변경 (#84)

.github/workflows/pull-request-test-v1.yml, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/OrderController.kt, build.gradle.kts
|Overall Project|37.71% **`-0.19%`**|:x:|
|:-|:-|:-:|
|Files changed|0%|:x:|
<br>
|File|Coverage||
|:-|:-|:-:|
|[OrderController.kt](https://github.com/FC-InnerCircle-ICD2/O2O-BE/blob/350a7c60c45ab05cafe270613e1164ab0f801a17/application-client%2Fsrc%2Fmain%2Fkotlin%2Forg%2Ffastcampus%2Fapplicationclient%2Forder%2Fcontroller%2FOrderController.kt)|10.98% **`-13.41%`**|:x:|
application-client 모듈의 코드 커버리지가 `37.71` 퍼센트를 의미합니다.
OrderController.kt 파일의 코드 커버리지는 `10.98` 퍼센트를 의미합니다.
커버리지 옆의 음수값은 현재 커밋 또는 풀 요청에서 `변경한 내용에만` 기반하여 테스트 커버리지의 차이를 계산합니다.
예를 들어, 10줄의 코드가 수정되거나 추가되고 그 중 8줄이 단위 테스트에서 다루어지면 커버리지 옆의 음수값은 -20%가 되어 새로 변경된 코드의 20%가 테스트되지 않았음을 나타냅니다.
`해당 라이브러리에는 한계점이 있습니다.`
기존의 코드를 수정하지 않고, 단위 테스트를 더 추가할 경우 커버리지 옆의 음수값은 업데이트되지 않습니다. 
추가, 수정된 코드의 변경된 코드 라인만 고려하여 변경되지 않은 기존 코드의 커버리지 개선을 추적할 메커니즘이 없기 …
=> [Fix] 주문 내역 조회 authMember 추가

application-admin/Dockerfile, application-client/Dockerfile
=> [Chore] 타임존 설정 (#95)

application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/OrderController.kt
- AuthMember 정상적으로 받도록 @JwtAuthenticated 추가
=> [Fix] API 인증

domains/payment/src/main/kotlin/org/fastcampus/payment/entity/Payment.kt, flyway/migration/V2__add_status_column_to_payment_and_update_init_data.sql, infrastructure/payment-postgres/src/main/kotlin/org/fastcampus/payment/postgres/entity/PaymentJpaEntity.kt
=> [Feat] Payment 상태값 추가 (#99)

docker-compose.yml
- postgresql 타임존 Asia/Seoul 설정
=> [Chore] docker-compose.yml 수정

flyway/migration/V3__insert_sample_data_into_members.sql
=> [Chore] member 테스트 데이터 (#105)

application-client/src/main/kotlin/org/fastcampus/applicationclient/banner/controller/BannerController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/banner/controller/dto/response/BannerResponse.kt, application-client/src/main/resources/logback-spring.xml, infrastructure/order-postgres/docker/Dockerfile
- Fix: logback-spring.xml 에 profile dev 추가
- Remove: order-postgres Docker 폴더 삭제
=> [Test] 프론트엔드 통신 확인을 위한 api/v1/banner API 추가 (#107)

application-client/src/main/kotlin/org/fastcampus/applicationclient/payment/controller/PaymentController.kt
=> [Fix] 인증 어노테이션 추가 (#110)

.github/workflows/develop-client-deploy-v1.yml
=> Chore: develop-client-deploy-v1.yml 수정

application-admin/src/main/kotlin/org/fastcampus/applicationadmin/order/controller/OrderController.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/order/service/OrderService.kt, application-client/build.gradle.kts, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/OrderController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/OrderCancellationService.kt, application-client/src/main/resources/http/order.http, flyway/migration/V5__create_refund_table.sql, infrastructure/order-postgres/src/main/kotlin/org/fastcampus/order/postgres/entity/OrderJpaEntity.kt
주문관련해서 동시성 이슈를 낙관적락으로 처리하려 했으나 다른 방식으로 풀어나가기로 하여 해당 부분을 제거
=> [Fix] 주문취소 관련 동시성 로직 수정 (#11)

infrastructure/store-mongo/docker/stores.json
=> [Feat] 초기데이터 수정

application-admin/src/main/kotlin/org/fastcampus/applicationadmin/config/SwaggerConfig.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/config/security/SecurityConfig.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/sse/SseController.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/sse/docs/OrderNotification.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/sse/docs/SseControllerDocs.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/config/SwaggerConfig.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/OrderController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/docs/OrderControllerDocs.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/docs/OrderCreation.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/payment/controller/PaymentController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/payment/controller/docs/PaymentApprove.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/payment/controller/docs/PaymentControllerDocs.kt
- 토큰 설정 가능하도록 SwaggerConfig 변경
- 점주측 Swagger 접근 가능하도록 SecurityConfig 변경
- 주문생성,결제승인,주문알림 swagger 작성
=> [Docs] 주문생성,결제승인,주문알림 swagger 추가 (#158)

application-admin/src/test/kotlin/org/fastcampus/applicationadmin/fixture/StoreFixture.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/dto/response/StoreDetailsResponse.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/mapper/StoreMapper.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/fixture/StoreFixture.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/order/service/OrderCreationServiceTest.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/store/service/StoreServiceTest.kt, domains/store/src/main/kotlin/org/fastcampus/store/entity/Menu.kt, domains/store/src/main/kotlin/org/fastcampus/store/entity/Store.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/document/MenuDocument.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/document/StoreDocument.kt
- 상점 조회시 최소주문금액
- 메뉴 카테고리 조회시 메뉴당 isBest, isManyOrder 추가.
=> [Refactor] 반환 값 변경

application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/OrderService.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/OrderValidator.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/order/service/OrderCreationServiceTest.kt, domains/order/src/main/kotlin/org/fastcampus/order/exception/OrderException.kt, flyway/migration/V9__update_order_id.sql
- 주문 최소금액 확인하도록 수정
- 주문번호 이쁘게 수정
- 기존 주문번호 UPDATE
=> [Feat] 주문생성 수정 (#177)

application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/controller/CartController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/controller/dto/response/CartResponse.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/service/CartMenuInsertionService.kt, application-client/src/main/resources/http/order.http
- 로그인 유저의 현재 장바구니 목록 조회
- order http 추가
- request mapping "/api/v1/carts" 복수형으로 변경
=> [Feat] 장바구니 조회 API (#160)

application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/controller/CartController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/controller/dto/request/CartUpdateRequest.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/controller/dto/response/CartUpdateResponse.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/service/CartMenuInsertionService.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/service/CartReadService.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/service/CartUpdateService.kt, application-client/src/main/resources/http/order.http, domains/cart/src/main/kotlin/org/fastcampus/cart/exception/CartException.kt
- 장바구니 메뉴 수량 변경
- order http 수정
- 서비스클래스 분리
=> [Feat] 장바구니 수정(수량만) API (#171)

application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/controller/CartController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/controller/dto/request/CartMenuDeletionRequest.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/cart/service/CartMenuDeletionService.kt, application-client/src/main/resources/http/order.http
- 장바구니 추가된 메뉴를 삭제
- order http 추가
=> [Feat] 장바구니 삭제 API (#161)

application-admin/build.gradle.kts, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/dashboard/controller/DashboardController.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/dashboard/dto/response/DashboardResponse.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/dashboard/service/DashboardService.kt, application-admin/src/main/resources/http/dashboard.http, application-admin/src/test/kotlin/org/fastcampus/applicationadmin/dashboard/service/DashboardServiceTest.kt, domains/order/src/main/kotlin/org/fastcampus/order/repository/OrderRepository.kt, infrastructure/order-postgres/src/main/kotlin/org/fastcampus/order/postgres/repository/OrderJpaRepository.kt, infrastructure/order-postgres/src/main/kotlin/org/fastcampus/order/postgres/repository/OrderJpaRepositoryCustom.kt
- 점주 앱의 대시보드 api 개발
- 두 가지의 상태 {주문, 매출}
- 각 상태에 따른 다른 응답
=> [Feature] 점주 대시보드 개발(#214)

application-client/build.gradle.kts, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/StoreController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/service/StoreService.kt, application-client/src/main/resources/http/store.http, common/src/main/kotlin/org/fastcampus/common/dto/CursorBasedDTO.kt, domains/store/src/main/kotlin/org/fastcampus/store/repository/StoreRepository.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/document/StoreDocument.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/repository/StoreMongoRepositoryCustom.kt
- 기존에 cursor 기반으로 작동하지 않던부분 변경
- 복합키 사용(스토어 아이디 + 거리)
- 해당 복합키를 nextCursor 로 기반해서 불러오기.
=> [Refactor] store 목록 가져오는 부분 수정

application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/StoreController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/dto/request/StoreRequest.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/mapper/StoreMapper.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/service/StoreService.kt, application-client/src/main/resources/http/store.http, application-client/src/test/kotlin/org/fastcampus/applicationclient/store/service/StoreServiceTest.kt
=> [Refactor] store rating, reviewCount 고정값에서 변경

application-client/src/main/kotlin/org/fastcampus/applicationclient/store/mapper/StoreMapper.kt, application-client/src/main/resources/http/store.http
=> [Refactor] menu price 값 오류

application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/StoreController.kt
=> [Refactor] order type 제거

application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/StoreController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/service/StoreService.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/store/service/StoreServiceTest.kt, domains/store/src/main/kotlin/org/fastcampus/store/repository/StoreRepository.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/repository/StoreMongoRepositoryCustom.kt
=> [Refactor] 좌표계산 오류 수정

application-client/src/main/kotlin/org/fastcampus/applicationclient/store/controller/StoreController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/store/service/StoreService.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/store/service/StoreServiceTest.kt, domains/store/src/main/kotlin/org/fastcampus/store/repository/StoreRepository.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/repository/StoreMongoRepositoryCustom.kt
=> [Chore] 좌표계산

application-client/src/main/kotlin/org/fastcampus/applicationclient/store/mapper/StoreExtensions.kt
- 기존에 km 단위로 계산하던것 m 단위로 변경해서 계산하도록 수정
=> [Chore] 배달예상 시간 수정

application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/OrderController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/OrderCreationService.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/OrderService.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/order/service/OrderCreationServiceTest.kt, domains/order/src/main/kotlin/org/fastcampus/order/entity/OrderMenu.kt
=> [Refactor] 주문생성 리팩토링 (#252)

application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/OrderCreationService.kt
=> [Feat] 주문객체 조립(변수명 수정) (#259)

application-admin/src/main/kotlin/org/fastcampus/applicationadmin/order/service/event/OrderCancellationReceiver.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/OrderCancellationService.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/event/OrderCancellationEvent.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/event/OrderCancellationEventHandler.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/order/service/OrderCancellationServiceTest.kt, infrastructure/order-redis/src/main/kotlin/org/fastcampus/applicationadmin/event/RedisMessageConfig.kt, infrastructure/order-redis/src/main/kotlin/org/fastcampus/applicationclient/event/OrderCancellationSender.kt
=> [Feat] 주문취소 알림 (#264)

application-admin/src/main/kotlin/org/fastcampus/applicationadmin/sse/SseController.kt
=> [Feat] SSE 타임아웃 시간 수정

application-admin/src/main/kotlin/org/fastcampus/applicationadmin/ApplicationAdminApplication.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/sse/SseController.kt, application-admin/src/main/kotlin/org/fastcampus/applicationadmin/sse/SseManager.kt
=> [Feat] SSE 설정 테스트

application-admin/src/main/kotlin/org/fastcampus/applicationadmin/sse/SseManager.kt
=> [Feat] SSE PING

application-client/src/main/kotlin/org/fastcampus/applicationclient/payment/service/PaymentService.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/payment/service/PaymentServiceTest.kt
=> [Fix] PG 구현 임시 주석처리 (#277)

application-client/src/main/kotlin/org/fastcampus/applicationclient/ApplicationClientApplication.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/payment/service/PaymentService.kt, infrastructure/external-pg-toss-payments/src/main/kotlin/org/fastcampus/payment/gateway/client/TossPaymentsClient.kt, infrastructure/external-pg-toss-payments/src/main/kotlin/org/fastcampus/payment/gateway/config/TossPaymentsClientConfig.kt, infrastructure/external-pg-toss-payments/src/main/kotlin/org/fastcampus/payment/gateway/error/TossPaymentsApproveErrorResponse.kt, infrastructure/external-pg-toss-payments/src/main/kotlin/org/fastcampus/payment/gateway/error/TossPaymentsErrorDecoder.kt, infrastructure/external-pg-toss-payments/src/main/kotlin/org/fastcampus/payment/gateway/error/TossPaymentsException.kt
- 패키지 이동
- config 설정 feign client 에만 적용되도록 변경(feign client 전용 objectMapper가 전체 애플리케이션에 영향)
=> [Fix] 결제승인 설정 변경

application-client/src/main/kotlin/org/fastcampus/applicationclient/payment/service/PaymentService.kt, application-client/src/test/kotlin/org/fastcampus/applicationclient/payment/service/PaymentServiceTest.kt
- 결제완료시 mongo 의 주문 상태변경을 위한 이벤트 발행 추가
=> [Feat] 결제완료시 주문 상태변경 이벤트

application-client/src/main/kotlin/org/fastcampus/applicationclient/member/dto/response/MemberInfoResponse.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/member/service/MemberService.kt
=> [Feat] 사용자 기본주소 추가

infrastructure/store-redis/src/main/kotlin/org/fastcampus/store/redis/repository/StoreRedisRepositoryImpl.kt
=> [Feat] trend 검색어 expire 시간 주석처리

application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/OrderController.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/controller/docs/OrderCreation.kt, application-client/src/main/kotlin/org/fastcampus/applicationclient/order/service/OrderCreationService.kt, application-client/src/main/resources/http/order.http, application-client/src/test/kotlin/org/fastcampus/applicationclient/order/service/OrderCreationServiceTest.kt, domains/order/src/main/kotlin/org/fastcampus/order/exception/OrderException.kt, domains/store/src/main/kotlin/org/fastcampus/store/repository/StoreRepository.kt, infrastructure/store-mongo/src/main/kotlin/org/fastcampus/store/mongo/repository/StoreMongoRepositoryCustom.kt
=> [Feat] 주문지 거리제한

infrastructure/store-redis/src/main/kotlin/org/fastcampus/store/redis/repository/StoreRedisRepositoryImpl.kt
=> [Feat] 트렌드 검색어 상위 6개로 수정
